(()=>{const $=s=>document.querySelector(s);let csrf='',manager=false,sections=[];
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options,headers:{...(options.headers||{})}});if(r.status===401){location.replace('/login.html');throw Error('authentication_required')}const data=r.status===204?{}:await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||'request_failed');return data}
function status(message){$('#status').textContent=message}
function report(error){const messages={forbidden:'Your college role cannot perform this action.',invalid_term:'Check the term name, code, and date range.',term_code_exists:'That term code already exists in this college.',invalid_course:'Check the course code, title, and credit value.',course_code_exists:'That course code already exists in this college.',invalid_section:'Check the section details and capacity.',academic_resource_not_found:'Choose a course and term belonging to this college.',faculty_membership_required:'Choose a faculty member of this college.',section_code_exists:'That section code already exists for the course and term.',invalid_student_selection:'Select one or more active students.',section_capacity_exceeded:'The section capacity would be exceeded.',student_selection_invalid:'One or more selected students are not active in this college.',invalid_attendance_records:'Every student needs a valid attendance status.',attendance_roster_mismatch:'The roster changed. Reload it before saving.',invalid_attendance_query:'Choose a valid date and section.'};status(messages[error.message]||'The request could not be completed. Check your access and try again.')}
function options(select,items,label,value,current=''){select.replaceChildren();if(!items.length){const empty=document.createElement('option');empty.value='';empty.textContent='No options available';select.append(empty);return}for(const item of items){const option=document.createElement('option');option.value=item[value];option.textContent=label(item);if(option.value===current)option.selected=true;select.append(option)}}
async function loadData(){
const [termsData,coursesData,sectionData]=await Promise.all([api('/api/academic/terms'),api('/api/academic/courses'),api('/api/academic/sections')]);
const terms=termsData.terms,courses=coursesData.courses;sections=sectionData.sections;
$('#termCount').textContent=terms.length;$('#courseCount').textContent=courses.length;$('#sectionCount').textContent=sections.length;
$('#seatCount').textContent=sections.reduce((sum,s)=>sum+Number(s.enrolled_count),0);
options($('#sectionForm').elements.courseId,courses,c=>c.code+' · '+c.title,'id');
options($('#sectionForm').elements.termId,terms,t=>t.name+' · '+t.code,'id');
options($('#enrollmentForm').elements.sectionId,sections,s=>s.course_code+' · '+s.section_code+' · '+s.term_code,'id');
options($('#attendanceSection'),sections,s=>s.course_code+' · '+s.section_code+' · '+s.term_code,'id',$('#attendanceSection').value);
}
async function loadRoster(){
const sectionId=$('#attendanceSection').value,date=$('#attendanceDate').value;if(!sectionId||!date){status('Choose a section and date.');return}
try{const data=await api('/api/attendance?sectionId='+encodeURIComponent(sectionId)+'&date='+encodeURIComponent(date));const tbody=$('#roster');tbody.replaceChildren();
for(const student of data.students){const row=document.createElement('tr'),name=document.createElement('td'),full=document.createElement('b');full.className='student-name';full.textContent=student.first_name+' '+student.last_name;name.append(full);const number=document.createElement('td');number.textContent=student.student_number;const attendance=document.createElement('td'),select=document.createElement('select');select.dataset.studentId=student.student_id;select.setAttribute('aria-label','Attendance for '+student.first_name+' '+student.last_name);for(const value of ['unmarked','present','absent','late','excused']){const option=document.createElement('option');option.value=value;option.textContent=value[0].toUpperCase()+value.slice(1);select.append(option)}select.value=student.status;attendance.append(select);row.append(name,number,attendance);tbody.append(row)}
if(!data.students.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=3;cell.textContent='No active students are enrolled in this section yet.';row.append(cell);tbody.append(row)}
status(data.students.length+' enrolled student'+(data.students.length===1?'':'s')+' loaded. Mark each student before saving.');
}catch(error){report(error)}
}
async function start(){
try{const session=await api('/api/session');csrf=session.csrfToken;manager=['college_admin','registrar'].includes(session.college.role);$('#collegeBadge').textContent=session.college.name+' · '+session.college.role.replace('_',' ');
$('#setupPanels').hidden=!manager;$('#sectionPanel').hidden=!manager;$('#enrollmentPanel').hidden=!manager;
const today=new Date(),localDate=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);$('#attendanceDate').value=localDate;
await loadData();
if(manager){const faculty=await api('/api/academic/faculty');const instructor=$('#sectionForm').elements.instructorId;for(const person of faculty.faculty){const option=document.createElement('option');option.value=person.id;option.textContent=person.display_name+' · '+person.email;instructor.append(option)}
const students=await api('/api/students');const list=$('#enrollmentForm').elements.studentIds;for(const student of students.students){const option=document.createElement('option');option.value=student.id;option.textContent=student.student_number+' · '+student.first_name+' '+student.last_name;list.append(option)}}
}catch(error){report(error)}
}
$('#termForm').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{await api('/api/academic/terms',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({code:f.get('code'),name:f.get('name'),startsOn:f.get('startsOn'),endsOn:f.get('endsOn')})});event.currentTarget.reset();status('Academic term created.');await loadData()}catch(error){report(error)}});
$('#courseForm').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{await api('/api/academic/courses',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({code:f.get('code'),title:f.get('title'),credits:f.get('credits')})});event.currentTarget.reset();event.currentTarget.elements.credits.value='3';status('Course added to the catalog.');await loadData()}catch(error){report(error)}});
$('#sectionForm').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{await api('/api/academic/sections',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({courseId:f.get('courseId'),termId:f.get('termId'),sectionCode:f.get('sectionCode'),instructorId:f.get('instructorId')||null,capacity:f.get('capacity')})});event.currentTarget.reset();event.currentTarget.elements.capacity.value='60';status('Course section created. Enroll students to open its attendance register.');await loadData()}catch(error){report(error)}});
$('#enrollmentForm').addEventListener('submit',async event=>{event.preventDefault();const f=new FormData(event.currentTarget),ids=[...event.currentTarget.elements.studentIds.selectedOptions].map(option=>option.value);try{const result=await api('/api/academic/sections/'+encodeURIComponent(f.get('sectionId'))+'/enrollments',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({studentIds:ids})});status(result.enrolled+' new student'+(result.enrolled===1?'':'s')+' enrolled.');await loadData()}catch(error){report(error)}});
$('#loadRoster').onclick=loadRoster;$('#attendanceSection').addEventListener('change',loadRoster);$('#attendanceDate').addEventListener('change',loadRoster);
$('#saveAttendance').onclick=async()=>{const rows=[...$('#roster').querySelectorAll('select[data-student-id]')],records=rows.map(select=>({studentId:select.dataset.studentId,status:select.value}));if(records.some(record=>record.status==='unmarked')){status('Mark every student present, absent, late, or excused before saving.');return}try{const result=await api('/api/attendance?sectionId='+encodeURIComponent($('#attendanceSection').value)+'&date='+encodeURIComponent($('#attendanceDate').value),{method:'PUT',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({records,note:$('#attendanceNote').value})});status('Attendance saved for '+result.saved+' students.');await loadRoster()}catch(error){report(error)}};
$('#signout').onclick=async()=>{try{await api('/api/logout',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:'{}'})}finally{location.replace('/login.html')}};start()})();
